### ISSUE TITLE
建议也做个excel导入成strings.xml的功能

### ISSUE THREAD

**Issue by DanteAndroid** [zhaoyubetter/ExtractMultiString#1]

**Comment by zhaoyubetter** [comment]
excel 转换成 strings.xml 考虑过，但 千万不能全盘覆盖，res/values目录，有些资源可能是不要翻译的，在代码中我过滤掉了 translatable="true" 的资源；

**Comment by zhaoyubetter** [comment]
功能已添加！1.1.1版本。
